version: '3.6'
services:
  crowdsec:
    image: crowdsecurity/crowdsec:latest
    container_name: ddev-${DDEV_SITENAME}-crowdsec
    hostname: ${DDEV_SITENAME}-crowdsec
    # These labels ensure this service is discoverable by ddev.
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    volumes:
      - "../bouncer-keys:/etc/crowdsec/bouncer-keys"
    environment:
      - DISABLE_AGENT=true
    ports:
      - "8080"
  web:
    links:
      - crowdsec:crowdsec
